### ISSUE TITLE
Write the ingestor

### ISSUE THREAD

**Issue by sidvenu** [thewebhookcompany/thewebhookcompany#1]
Flow of the ingestor:

1. Listens to any incoming request
1. Transforms the reqd data into a byte array (should also consider X-Forwarded- headers if behind a proxy)
1. Publish the byte array into `{origin}-incoming` topic of the event store.

**Comment by shyam-king** [comment]
I think we should describe these more?

**Comment by sidvenu** [comment]
Ye will edit the description
