### ISSUE TITLE
MQ topics represented as class over string

### ISSUE THREAD

**Issue by shyam-king** [thewebhookcompany/thewebhookcompany#3]
Message queue topics should not be accepted as raw strings in code. This can lead to unintended collisions in topic names which can lead to unexpected behaviour if the consumers don't have proper validations in place.

To prevent this we will need to establish a nomenclature for topics to prevent two use-cases to end up with the same topic name. 

To begin with we may proceed with a nomenclature:
`{variable}-{intention}`

Here `variable` is a unique string representing some sub-entity related to the intention of the message, and `intention` can be a predefined enum of strings that describe various kind of messages.

Thus, instead of raw `String` type for topics, we can create a wrapper class `Topic` which encapsulates `variable` and `intention` and resolves to a string for the underlying implementation of message queues.

**Comment by sidvenu** [comment]
Is this still applicable now that our topics are simplified to only the intention part as of now? Like `incoming`, `outgoing` etc.

**Comment by shyam-king** [comment]
I guess not
